[package]
name = "hecs_game"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.5"
glam = "0.29.2"
hecs = { version = "0.10.5", features = ["std", "macros"] }
hecs_engine.git = "https://github.com/BrackenLo/hecs_engine.git"
log = "0.4.22"
rand = "0.8.5"
